title: Mario_OOP
description: "August 2023 to June 2024"
owner_name: Daniel Fitzwilliam
github_username: DanielFitzwilliam
github_repo: "Mario_OOP"
baseurl: "/Mario_OOP"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}
    - { platform: github, user_url: "https://github.com/h4seeb-cmd"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
header_pages:
  - 2024-01-08-CSSE-oop-game-levels2.md
  - 2023-11-27-CSSE-oop-game-levels.md
  - AC_csse.md